name: Fourth Workflow # Name of the workflow
on:  # Trigger the workflow manually
    push: # Trigger the workflow on push
        branches: # Specify the branches to trigger the workflow
            - main # Main branch
            - dev # Development branch
    
    pull_request: # Trigger the workflow on pull request
        types: # Specify the types of pull requests to trigger the workflow
            - opened # When a pull request is opened
            - synchronize # When a pull request is synchronized (updated)
            - reopened # When a pull request is reopened
            
            
# Define the jobs that will run in this workflow
# Each job runs in a separate environment 

jobs: 
  first-job: # Name of the job
    runs-on: ubuntu-latest # The environment where the job will run
    steps: # Steps to be executed in the job
      - name: Print greeting # Step name
        run: echo "${{toJson(github)}}"  # GitHub context variable