name: second-workflow # Name of the workflow

on: [push, workflow_dispatch] # Trigger the workflow on push or manually

jobs:
  second-job: # Name of the job
    runs-on: ubuntu-latest # The environment where the job will run
    steps: # Steps to be executed in the job
      - name: Get Code from GitHub # Step name
        uses: actions/checkout@v4
        with: # Inputs for the action
          node-version: 18 # Node.js version to be used

      - name: Install Dependencies # Step name
        run: npm install # Command to install dependencies

      - name: Run Tests # Step name
        run: npm test # Command to run tests

  third-job: # Name of the new job
    runs-on: ubuntu-latest # The environment where the job will run
    needs: second-job # Ensure this job runs only after second-job is complete
    steps: # Steps to be executed in the job
      - name: Get Code from GitHub # Step name
        uses: actions/checkout@v4

      - name: Build Project # Step name
        run: npm run build # Command to build the project

      - name: Deploy Application # Step name
        run: echo "Deploying application..." # Replace with actual deployment command
        