name: Third Workflow # Name of the workflow
on: workflow_dispatch # Trigger the workflow manually

# Define the jobs that will run in this workflow
# Each job runs in a separate environment 
env: # Define environment variables
  MY_ENV_VAR: "Prod" # Environment variable
  MY_ENV_VAR2: "Test" # Environment variable 

jobs:  
  first-job: # Name of the job
    runs-on: ubuntu-latest # The environment where the job will run
    outputs: # Define outputs for the job
      greeting: ${{ steps.greeting.outputs.greeting }} # Output from the step
    steps: # Steps to be executed in the job
      - name: Set output variable
        id: greeting
        run: echo "greeting=$(pwsh -Command 'Write-Output "Hello from PowerShell"')" >> $GITHUB_OUTPUT
  
  second-job: # Name of the job
    runs-on: ubuntu-latest # The environment where the job will run
    needs: first-job # Ensure this job runs only after first-job is complete
    steps: # Steps to be executed in the job
      - name: Print greeting # Step name
        run: echo "${{ needs.first-job.outputs.greeting }}" # Command to print the output from first-job
      - name: Print greeting # Step name
        run: echo "Hello From ${{ env.MY_ENV_VAR }}" # Command to print the output from first-job